--- 
apiVersion: v1
kind: Namespace
metadata:
  name: challenge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: challenge
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
  namespace: challenge
  labels: 
    app: nginx-service
spec:
  selector:
    app: nginx 
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP
 